ALTER TABLE currency ADD COLUMN version int NOT NULL DEFAULT 0;

ALTER TABLE country ADD COLUMN version int NOT NULL DEFAULT 0;

ALTER TABLE state ADD COLUMN version int NOT NULL DEFAULT 0;

ALTER TABLE city ADD COLUMN version int NOT NULL DEFAULT 0;
