management:
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 8080
  servlet:
    context-path: /api/catalog

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: rootpassword
      database: admin