version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432      

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sacco.andres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80
    depends_on:
      - db
